/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package magazzino;

/**
 *
 * @author taboada.taddeo
 */
public class AggiuntaProdotto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiuntaProdotto.class.getName());

    /**
     * Creates new form AggiuntaProdotto
     */
    public AggiuntaProdotto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTitolo.setBackground(new java.awt.Color(0, 51, 51));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Georgia Pro", 1, 48)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Aggiungi un Prodotto");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentro.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jLabel1.setText("jLabel1");
        pnlCentro.add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnlCentro.add(jTextField1);

        jLabel2.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");
        pnlCentro.add(jLabel2);

        jTextField2.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jTextField2.setText("jTextField2");
        pnlCentro.add(jTextField2);

        jLabel3.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jLabel3.setText("jLabel3");
        pnlCentro.add(jLabel3);

        jTextField3.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jTextField3.setText("jTextField3");
        pnlCentro.add(jTextField3);

        jLabel4.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jLabel4.setText("jLabel4");
        pnlCentro.add(jLabel4);

        jTextField4.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jTextField4.setText("jTextField4");
        pnlCentro.add(jTextField4);

        jLabel5.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jLabel5.setText("jLabel5");
        pnlCentro.add(jLabel5);

        jTextField5.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jTextField5.setText("jTextField5");
        pnlCentro.add(jTextField5);

        jLabel6.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jLabel6.setText("jLabel6");
        pnlCentro.add(jLabel6);

        jTextField6.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        jTextField6.setText("jTextField6");
        pnlCentro.add(jTextField6);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setBackground(new java.awt.Color(153, 255, 153));
        btnConferma.setFont(new java.awt.Font("Georgia Pro", 1, 24)); // NOI18N
        btnConferma.setText("Conferma");
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AggiuntaProdotto dialog = new AggiuntaProdotto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlTitolo;
    // End of variables declaration//GEN-END:variables
}
