/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package magazzino;

/**
 *
 * @author taboada.taddeo
 */
public class AggiuntaProdotto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiuntaProdotto.class.getName());
    private Prodotto p;

    /**
     * Creates new form AggiuntaProdotto
     */
    public AggiuntaProdotto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void modificaProdotto(int id) {
        setTitle("Modifica Prodotto");
        lblTitolo.setText("Modifica un Prodotto");
        txtId.setText(String.valueOf(id));
        txtId.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPrezzoA = new javax.swing.JLabel();
        txtPrezzoA = new javax.swing.JTextField();
        lblPrezzoV = new javax.swing.JLabel();
        txtPrezzoV = new javax.swing.JTextField();
        lblScorta = new javax.swing.JLabel();
        txtScorta = new javax.swing.JTextField();
        lblScortaMin = new javax.swing.JLabel();
        txtScortaMin = new javax.swing.JTextField();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aggiunta Prodotto");
        setPreferredSize(new java.awt.Dimension(700, 500));

        pnlTitolo.setBackground(new java.awt.Color(0, 77, 51));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Georgia Pro", 1, 48)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Aggiungi un Prodotto");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentro.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        lblId.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        lblId.setText("ID Prodotto:");
        pnlCentro.add(lblId);

        txtId.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        pnlCentro.add(txtId);

        lblNome.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        lblNome.setText("Nome Prodotto:");
        pnlCentro.add(lblNome);

        txtNome.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        pnlCentro.add(txtNome);

        lblPrezzoA.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        lblPrezzoA.setText("Prezzo di Acquisto:");
        pnlCentro.add(lblPrezzoA);

        txtPrezzoA.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        pnlCentro.add(txtPrezzoA);

        lblPrezzoV.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        lblPrezzoV.setText("Prezzo di Vendita:");
        pnlCentro.add(lblPrezzoV);

        txtPrezzoV.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        pnlCentro.add(txtPrezzoV);

        lblScorta.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        lblScorta.setText("Scorta del Prodotto:");
        pnlCentro.add(lblScorta);

        txtScorta.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        pnlCentro.add(txtScorta);

        lblScortaMin.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        lblScortaMin.setText("Scorta minima del Prodotto:");
        pnlCentro.add(lblScortaMin);

        txtScortaMin.setFont(new java.awt.Font("Georgia Pro", 1, 18)); // NOI18N
        pnlCentro.add(txtScortaMin);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setBackground(new java.awt.Color(100, 255, 100));
        btnConferma.setFont(new java.awt.Font("Georgia Pro", 1, 24)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        int id = Integer.parseInt(txtId.getText());
        String nome = txtNome.getText();
        int prezzoA = Integer.parseInt(txtPrezzoA.getText());
        int prezzoV = Integer.parseInt(txtPrezzoV.getText());
        int scorta = Integer.parseInt(txtScorta.getText());
        int scortaMin = Integer.parseInt(txtScortaMin.getText());
        
        p = new Prodotto(id, nome, prezzoA, prezzoV, scorta, scortaMin);
        
        dispose();
    }//GEN-LAST:event_btnConfermaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AggiuntaProdotto dialog = new AggiuntaProdotto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Prodotto getP() {
        return p;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPrezzoA;
    private javax.swing.JLabel lblPrezzoV;
    private javax.swing.JLabel lblScorta;
    private javax.swing.JLabel lblScortaMin;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrezzoA;
    private javax.swing.JTextField txtPrezzoV;
    private javax.swing.JTextField txtScorta;
    private javax.swing.JTextField txtScortaMin;
    // End of variables declaration//GEN-END:variables
}
