package magazzino;

import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author taboada.taddeo
 */
public class FrameMagazzino extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMagazzino.class.getName());
    private RaccoltaProdotti rP;
    private DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form FrameMagazzino
     */
    public FrameMagazzino() {
        initComponents();
        rP = new RaccoltaProdotti();
        impostaTabella();
    }
    
    private void impostaTabella() {
        tblProdotti.setSize(pnlProdotti.getWidth(), pnlProdotti.getHeight());
        tblProdotti.setRowHeight(pnlProdotti.getHeight() / tblProdotti.getRowCount());
        tblProdotti.setModel(model);
    }
    
    public void aggiornaGite() { 
        model.setRowCount(0);

        for (Prodotto p : rP.getListaProdotti()) {
            //model.addRow(new Object[]{g.getId(), g.getLuogo()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlProdotti = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdotti = new javax.swing.JTable();
        pnlBottoni = new javax.swing.JPanel();
        btnRimuoviProdotto = new javax.swing.JButton();
        btnModificaProdotto = new javax.swing.JButton();
        btnAggiungiProdotto = new javax.swing.JButton();
        btnStatistiche = new javax.swing.JButton();
        btnControlloScorte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magazzino");
        setMinimumSize(new java.awt.Dimension(1000, 700));

        pnlTitolo.setBackground(new java.awt.Color(0, 77, 51));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Georgia Pro", 1, 48)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Magazzino");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        pnlProdotti.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prodotti", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia Pro", 1, 24))); // NOI18N
        pnlProdotti.setMinimumSize(new java.awt.Dimension(26, 400));
        pnlProdotti.setPreferredSize(new java.awt.Dimension(600, 700));
        pnlProdotti.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 625));

        tblProdotti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID prodotto", "Nome prodotto", "Prezzo acquisto prodotto", "Prezzo vendita prodotto", "Scorta prodotto", "Scorta minima prodotto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdotti.setMaximumSize(new java.awt.Dimension(2147483647, 700));
        tblProdotti.setMinimumSize(new java.awt.Dimension(90, 600));
        tblProdotti.setPreferredSize(new java.awt.Dimension(600, 690));
        jScrollPane1.setViewportView(tblProdotti);

        pnlProdotti.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlCentro.add(pnlProdotti, java.awt.BorderLayout.CENTER);

        pnlBottoni.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        pnlBottoni.setMinimumSize(new java.awt.Dimension(200, 625));
        pnlBottoni.setPreferredSize(new java.awt.Dimension(400, 625));
        pnlBottoni.setLayout(new java.awt.GridLayout(5, 1, 30, 30));

        btnRimuoviProdotto.setBackground(new java.awt.Color(207, 23, 0));
        btnRimuoviProdotto.setFont(new java.awt.Font("Georgia Pro", 1, 30)); // NOI18N
        btnRimuoviProdotto.setText("Rimuovi Prodotto");
        btnRimuoviProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRimuoviProdottoActionPerformed(evt);
            }
        });
        pnlBottoni.add(btnRimuoviProdotto);

        btnModificaProdotto.setBackground(new java.awt.Color(255, 250, 66));
        btnModificaProdotto.setFont(new java.awt.Font("Georgia Pro", 1, 30)); // NOI18N
        btnModificaProdotto.setText("Modifica Prodotto");
        btnModificaProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaProdottoActionPerformed(evt);
            }
        });
        pnlBottoni.add(btnModificaProdotto);

        btnAggiungiProdotto.setBackground(new java.awt.Color(77, 157, 51));
        btnAggiungiProdotto.setFont(new java.awt.Font("Georgia Pro", 1, 30)); // NOI18N
        btnAggiungiProdotto.setText("Aggiungi Prodotto");
        btnAggiungiProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiProdottoActionPerformed(evt);
            }
        });
        pnlBottoni.add(btnAggiungiProdotto);

        btnStatistiche.setBackground(new java.awt.Color(0, 102, 255));
        btnStatistiche.setFont(new java.awt.Font("Georgia Pro", 1, 30)); // NOI18N
        btnStatistiche.setText("Statistiche");
        btnStatistiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticheActionPerformed(evt);
            }
        });
        pnlBottoni.add(btnStatistiche);

        btnControlloScorte.setBackground(new java.awt.Color(116, 34, 179));
        btnControlloScorte.setFont(new java.awt.Font("Georgia Pro", 1, 30)); // NOI18N
        btnControlloScorte.setText("Controllo Scorte");
        btnControlloScorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlloScorteActionPerformed(evt);
            }
        });
        pnlBottoni.add(btnControlloScorte);

        pnlCentro.add(pnlBottoni, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnControlloScorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlloScorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnControlloScorteActionPerformed

    private void btnAggiungiProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiProdottoActionPerformed
        AggiuntaProdotto aP = new AggiuntaProdotto(this, true);
        aP.setLocationRelativeTo(null);
        aP.setVisible(true);
        
        rP.aggiungiProdotto(aP.getP());
    }//GEN-LAST:event_btnAggiungiProdottoActionPerformed

    private void btnRimuoviProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRimuoviProdottoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRimuoviProdottoActionPerformed

    private void btnModificaProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaProdottoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificaProdottoActionPerformed

    private void btnStatisticheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatisticheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameMagazzino().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungiProdotto;
    private javax.swing.JButton btnControlloScorte;
    private javax.swing.JButton btnModificaProdotto;
    private javax.swing.JButton btnRimuoviProdotto;
    private javax.swing.JButton btnStatistiche;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlBottoni;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlProdotti;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTable tblProdotti;
    // End of variables declaration//GEN-END:variables
}
