/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package magazzino;

/**
 *
 * @author taboada.taddeo
 */
public class VenditaProdotto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VenditaProdotto.class.getName());
    private RaccoltaProdotti rP;

    /**
     * Creates new form VenditaProdotto
     */
    public VenditaProdotto(java.awt.Frame parent, boolean modal, RaccoltaProdotti rP) {
        super(parent, modal);
        initComponents();
        this.rP = rP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblVendite = new javax.swing.JLabel();
        txtVendite = new javax.swing.JTextField();
        pnlConferma = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendita Prodotto");
        setMinimumSize(new java.awt.Dimension(700, 500));

        pnlTitolo.setBackground(new java.awt.Color(0, 77, 51));
        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setBackground(new java.awt.Color(0, 77, 51));
        lblTitolo.setFont(new java.awt.Font("Georgia Pro", 1, 48)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Vendi un Prodotto");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlCentro.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        lblId.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblId.setText("ID del prodotto:");
        pnlCentro.add(lblId);

        txtId.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pnlCentro.add(txtId);

        lblVendite.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblVendite.setText("Numero di prodotti da vendere:");
        pnlCentro.add(lblVendite);

        txtVendite.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pnlCentro.add(txtVendite);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlConferma.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlConferma.setLayout(new java.awt.BorderLayout());

        btnConferma.setBackground(new java.awt.Color(100, 255, 100));
        btnConferma.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.setPreferredSize(new java.awt.Dimension(137, 50));
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });
        pnlConferma.add(btnConferma, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlConferma, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
       int id = Integer.parseInt(txtId.getText());
       int vendite = Integer.parseInt(txtVendite.getText());
       Prodotto p = rP.cercaProdotto(id);
       
       if (p.getScorta() - vendite >= p.getScortaMin()) {
           p.setScorta(p.getScorta() - vendite); 
           p.setNumVendite(p.getNumVendite() + vendite);
           rP.eliminaProdotto(id);
           rP.aggiungiProdotto(p);
           dispose();
       }
    }//GEN-LAST:event_btnConfermaActionPerformed

    public RaccoltaProdotti getRP() {
        return rP;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JLabel lblVendite;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlConferma;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtVendite;
    // End of variables declaration//GEN-END:variables
}
